### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by Ladicek**
- fixed how the core test loop works, so that it doesn't inadvertently kill the process before the application is deployed
- added more metrics and improved how existing are collected
- polishing

I'd suggest reviewing each commit separately, I tried to structure them as independent units that follow in somewhat-logical succession.

Later, I will work on running this automatically. That will probably require some additional changes.

### CODE REVIEW

**Review by kenfinnigan — APPROVED** [review]
Seems ok to me, but @heiko-braun is the one that's worked with this the most so will leave it up to him to merge

**Comment by Ladicek** [comment]
@heiko-braun bump?

**Comment by Ladicek** [comment]
Thank you :-)

**Comment by heiko-braun** [comment]
Good work @Ladicek  and thanks for the improvements

**Pull request merged**
